# .github/workflows/main.yml
name: Liman Render Engine Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Getting Go Binaries
      uses: actions/setup-go@v2
      with:
          go-version: '1.24'
          
    - name: Build Application
      run: |
          go get -u && go mod tidy
          CGO_ENABLED=0 go build -o render

    - name: Install Upx
      run: |
        sudo apt-get install upx

    - name: Pack with Upx
      run: |
        upx --best render -o liman_render
          
    - name: Create Zip
      run: |
        zip -r /tmp/liman_render-${{ github.run_number }}.zip liman_render
        
    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
          files: /tmp/liman_render-${{ github.run_number }}.zip
          name: "Release ${{ github.run_number }}"
          tag_name: "release.${{ github.run_number }}"
          
